/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MergeResult {
  mergedText: string
  connectionPoints: Array<ConnectionPoint>
  totalChars: number
  filesMetadata: Array<FileMeta>
  skippedFiles: Array<string>
  encodingWarnings: Array<string>
}
export interface ConnectionPoint {
  id: string
  fileA: string
  fileB: string
  overlapLength: number
  overlapSnippet: string
  isAutoMerged: boolean
  position: number
}
export interface FileMeta {
  fileName: string
  fileSize: number
  encoding: string
}
/**
 * V4.0 napi 导出：链式重叠合并
 *
 * 读取文件 → 编码探测 → 文本归一化 → 最长后缀-前缀匹配 → 返回 MergeResult
 */
export declare function mergeFiles(paths: Array<string>, threshold: number): MergeResult
/**
 * V4.0 napi 导出：编码探测
 *
 * 读取文件并返回探测到的编码名称，不执行归一化
 */
export declare function detectEncoding(filePath: string): string
/**
 * V4.0 napi 导出：读取文件文本内容
 *
 * 读取文件 → 编码探测 → 返回解码后的 UTF-8 文本内容（不执行归一化）
 */
export declare function readFileText(filePath: string): string
