/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 文档排版结果 */
export interface FormatResult {
  formattedText: string
  paragraphCount: number
  protectedBlocks: number
  mergedBlocks: number
}
/**
 * 来源信息：记录段落来自哪个文件的哪一行
 * V3.0: 添加 #[napi(object)]，start_line 由 usize 改为 u32
 */
export interface SourceInfo {
  fileName: string
  startLine: number
}
/**
 * 重复组：一组相同的段落
 * V3.0: 添加 #[napi(object)]，occurrence_count 由 usize 改为 u32
 */
export interface DuplicateGroup {
  id: string
  contentHash: string
  snippet: string
  sources: Array<SourceInfo>
  occurrenceCount: number
}
/** 预览段落：用于右侧预览区的单个段落 */
export interface PreviewParagraph {
  id: string
  text: string
  contentHash: string
  sourceFiles: Array<string>
  isOriginal: boolean
}
/**
 * 文件元数据（前端显示用）
 * V3.0: 添加 #[napi(object)]，file_size/modified 由 u64 改为 u32
 */
export interface FileMeta {
  fileName: string
  fileSize: number
  modified: number
}
/**
 * 分析报告：扫描文件后的完整结果
 * V3.0: 添加 #[napi(object)]，total_files 由 usize 改为 u32
 */
export interface AnalysisReport {
  duplicateGroups: Array<DuplicateGroup>
  previewParagraphs: Array<PreviewParagraph>
  totalFiles: number
  /** 文件元数据列表（修复 BUG-006） */
  filesMetadata: Array<FileMeta>
}
/** 导出结果 */
export interface ExportResult {
  savedPath: string
}
/** V3.0 napi 导出：扫描并分析文件 */
export declare function scanFiles(paths: Array<string>): AnalysisReport
/** V3.0 napi 导出：文档排版（去硬回车） */
export declare function formatDocument(text: string): FormatResult
/** V3.1 napi 导出：编码探测（返回解码后的 UTF-8 文本，不执行归一化） */
export declare function detectEncoding(filePath: string): string
/**
 * V3.1 napi 导出：预处理文本的归一化 + 去重
 * 跳过文件 IO，直接对传入文本执行 TextNormalizer + InterFileDeduper
 */
export declare function scanPreprocessedTexts(texts: Array<string>, fileNames: Array<string>, fileSizes: Array<number>): AnalysisReport
